### ISSUE TITLE
Azure postgres db

### ISSUE THREAD

**Issue by heroic** [greencapitaltrade/terraform-jx-azure#3]
Create postgres db using terraform in the same vnet as the cluster.

**Comment by sauravbansal** [comment]
@heroic validate Azure Psql server. we can connect it from pods.

**Comment by heroic** [comment]
we're missing a read replica. should we make it highly available also, @sauravbansal ?

**Comment by heroic** [comment]
you'll possibly also want to check the config with: https://github.com/jfcoz/postgresqltuner
